/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.Statement;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sinxdell
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        setVisible(true);
        setSize(320, 630);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtUn = new javax.swing.JTextField();
        txtCur = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsn = new javax.swing.JTextField();
        txtCurrent = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNew = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        btnChange = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(42, 1275, 235, 22);

        jLabel1.setText("Enter Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(42, 1009, 92, 16);

        jLabel2.setText("Enter Current Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(42, 1111, 137, 16);

        jLabel3.setText("Enter New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(42, 1189, 118, 16);

        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(42, 1253, 103, 16);

        jButton1.setText("Change Password");
        getContentPane().add(jButton1);
        jButton1.setBounds(98, 1303, 135, 62);
        getContentPane().add(txtUn);
        txtUn.setBounds(42, 1065, 235, 24);
        getContentPane().add(txtCur);
        txtCur.setBounds(42, 1133, 235, 22);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(42, 1211, 235, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/profile.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 40, 130, 140);

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Enter Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 200, 110, 16);
        getContentPane().add(txtUsn);
        txtUsn.setBounds(40, 220, 230, 24);
        getContentPane().add(txtCurrent);
        txtCurrent.setBounds(40, 290, 230, 22);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Enter Current Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 270, 150, 16);

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Enter New Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 340, 140, 16);
        getContentPane().add(txtNew);
        txtNew.setBounds(40, 370, 230, 22);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Confirm Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 420, 110, 16);
        getContentPane().add(txtConfirm);
        txtConfirm.setBounds(40, 440, 230, 22);

        btnChange.setBackground(new java.awt.Color(204, 0, 204));
        btnChange.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnChange.setText("Change Password");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnChange);
        btnChange.setBounds(80, 500, 160, 90);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 102, 255));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 320, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        String uname = txtUsn.getText();
        String strpass = txtCurrent.getText();
        String newpass = txtNew.getText();
        String conpass = txtConfirm.getText();

        try {
            java.sql.Connection con = null;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/medical_sales", "root", "");

            PreparedStatement st = con.prepareStatement("Select * from login");
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                String usrname = rs.getString("email");
                String passwd = rs.getString("pwd");
                if (uname.equals(usrname) && strpass.equals(passwd)) {

                    if (newpass.equals(conpass)) {
                        PreparedStatement st1 = con.prepareStatement("UPDATE `login` SET `pwd`='" + newpass + "' WHERE `email` = '" + uname + "'");
                        st1.executeUpdate();
                        JOptionPane.showMessageDialog(null, "PASSWORD UPDATE SUCCESSFUL");
                        this.hide();

                        LoginScreen LS = new LoginScreen();

                        LS.show();

                    } else {
                        JOptionPane.showMessageDialog(null, "PLEASE CONFIRM PASSWORD");
                    }
                } else if (uname.equals("") && strpass.equals("") && newpass.equals("")) {
                    JOptionPane.showMessageDialog(null, "PLEASE ENTER ALL INFORMATION");
                } else {
                    JOptionPane.showMessageDialog(null, "USERNAME NOT FOUND");
                }
                st.close();

                con.close();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    public Connection getConnection() {
        Connection con;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/medical_sales", "root", "");
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JPasswordField txtCur;
    private javax.swing.JPasswordField txtCurrent;
    private javax.swing.JPasswordField txtNew;
    private javax.swing.JTextField txtUn;
    private javax.swing.JTextField txtUsn;
    // End of variables declaration//GEN-END:variables
}
