/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import java.sql.*;
import java.sql.Statement;
import MainPackage.DatabaseConnection;

import javax.swing.JOptionPane;
/**
 *
 * @author sinxdell
 */
public class RegisterScreen extends javax.swing.JFrame  {

    /**
     * Creates new form RegisterScreen
     */
    public RegisterScreen() {
        initComponents();
         setVisible(true);
              setSize(930,600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtPwd = new javax.swing.JTextField();
        txtRePwd = new javax.swing.JTextField();
        cbRegion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(930, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(930, 600));
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Dimuthu Tyre House");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 10, 440, 70);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/name.png"))); // NOI18N
        jLabel1.setText("Last Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(91, 280, 100, 30);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/name.png"))); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(91, 230, 120, 30);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/key.png"))); // NOI18N
        jLabel5.setText("Enter a Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(85, 410, 160, 30);

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/placeholder.png"))); // NOI18N
        jLabel6.setText("Regional Center");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(84, 360, 150, 30);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/key.png"))); // NOI18N
        jLabel7.setText("Re-enter Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(85, 460, 160, 30);
        getContentPane().add(txtfname);
        txtfname.setBounds(300, 230, 148, 24);
        getContentPane().add(txtlname);
        txtlname.setBounds(300, 280, 148, 24);
        getContentPane().add(txtPwd);
        txtPwd.setBounds(300, 410, 151, 24);
        getContentPane().add(txtRePwd);
        txtRePwd.setBounds(300, 460, 151, 24);

        cbRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "COLOMBO", "KANDY" }));
        getContentPane().add(cbRegion);
        cbRegion.setBounds(300, 360, 151, 26);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/profile.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(670, 80, 250, 170);

        btnRegister.setBackground(new java.awt.Color(204, 0, 204));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/enter (1).png"))); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(690, 496, 133, 43);
        getContentPane().add(txtemail);
        txtemail.setBounds(300, 180, 185, 24);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/email.png"))); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(94, 180, 120, 30);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 102, 255));
        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 930, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
      
        String email,fn,ln,address,batch,region,pwd;
     
        email = txtemail.getText();
        fn = txtfname.getText();
        ln = txtlname.getText();
        region = cbRegion.getSelectedItem().toString();
        pwd = txtPwd.getText();

         if(pwd.equals(txtRePwd.getText())){
        Connection con = null;
        try {
             DatabaseConnection test = new DatabaseConnection();
           
        Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost/dimuthu_tyre", "root", "");
          Statement stmt =  con.createStatement();
            String sqlQ = "insert into login values ('" + email + "','" + fn + "','" + ln + "','"+region+"','"+pwd+"')";
                stmt.executeUpdate(sqlQ);
                JOptionPane.showMessageDialog(null, "Employee Registered.");
                  this.hide();
             LoginScreen ls = new LoginScreen(); 
             ls.show();
                
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Database not Connected.");
        }
  
       }else{
             JOptionPane.showMessageDialog(null, "Password does not matches.");
         }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cbRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtPwd;
    private javax.swing.JTextField txtRePwd;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    // End of variables declaration//GEN-END:variables
}
